dist: precise
sudo: false

language: java

before_install:
    # Temp workaround to remove old references to codehaus repos
  - rm ~/.m2/settings.xml
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  
  
