language: java

before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  
  
